sonar.projectKey=GarlapatiBabitha_sonar-react-app
sonar.organization=garlapatibabitha

sonar.sources=src
sonar.exclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=https://sonarcloud.io