name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run Tests with Coverage
        run: npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=GarlapatiBabitha_sonar-react-app
            -Dsonar.organization=garlapatibabitha
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}